---
title: Starship Factory
repository: starshipfactory/starshipfactory.github.io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: false
    show_date: true
    read_time: true
    comments: false
    share: false
    related: true
    permalink: "/:year/:month/:day/:title/"
    breadcrumbs: false
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: false
subtitle: Dein Makerspace in Basel!
email: open@lists.starship-factory.ch
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
twitter_username: StarshipFactory
github_username: starshipfactory
minimal_mistakes_skin: default
search: true
logo: "/assets/images/logo.svg"
breadcrumbs: true
teaser: "/assets/images/logo.svg"
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/blog/page:num/"
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
- jekyll-redirect-from
author:
  name: First Lastname
  avatar: "/assets/images/bio-photo.jpg"
  bio: My awesome biography constrained to a sentence or two goes here.
  links:
  - label: Website
    icon: fas fa-fw fa-link
    url: https://
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/
footer:
  links:
  - label: Discourse
    icon: fab fa-brands fa-discourse
    url: https://discourse.starship-factory.ch
  - label: Signal
    icon: fab fa-fw fa-signal-messenger
    url: https://signal.group/#CjQKIIt5fkwCXHlImGzm41tTrf-6umAhyM7ENTpqW4Y0P4SHEhDgMyhI63oL7v3mTk0N7G3t
  - label: Kalender
    icon: fab fa-fw fa-calendar
    url: https://cloud.starship-factory.ch/apps/calendar/p/NBiqtDiWQZmAZYfq
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/StarshipFactory
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/starshipfactory
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/starship_factory
  - label: Facebook
    icon: fab fa-fw fa-facebook
    url: https://www.facebook.com/starshipfactory
  linked_pages:
  - label: Impressum
    url: "/impressum/"
  - label: Datenschutz
    url: "/datenschutz/"
  - label: Statuten
    url: "/organisation/statuten/"
  - label: Reglement/Charta
    url: "/organisation/reglement/"
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
